### ISSUE TITLE
Copy on Enter

### ISSUE THREAD

**Issue by Progress1** [merces/hem-copyas#1]
Now you can copy by pressing F5. Is it possible do it on Enter and then close dialog?

**Comment by merces** [comment]
Interesting way of thinking. I'll do some tests next week. Thanks for suggesting this! :)

**Comment by Progress1** [comment]
It's "normal" thinking ;-) if you choose something from the list you select it with Enter..
it's more natural as F5 + ESC and it's faster ;-)
